import { jsPDF } from "jspdf";

export async function generatePortfolioPDF(userData: any, matches: any[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primary = "#2563eb"; // Blue
  const secondary = "#4b5563"; // Gray
  
  // Header
  doc.setFillColor(31, 41, 55);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text(userData.name || userData.username, 20, 25);
  
  doc.setFontSize(10);
  doc.text("Technical Portfolio Analysis | Basely.Connect", 20, 32);
  
  // Content
  let y = 50;
  
  // Profile Section
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Technical Profile", 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const bioLines = doc.splitTextToSize(userData.bio || "No bio available", pageWidth - 40);
  doc.text(bioLines, 20, y);
  y += (bioLines.length * 5) + 5;
  
  doc.text(`Location: ${userData.location || "N/A"}`, 20, y);
  y += 5;
  doc.text(`Top Languages: ${userData.languages?.join(", ") || "N/A"}`, 20, y);
  y += 10;
  
  // Personal Statement
  if (userData.statement) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Personal Statement", 20, y);
    y += 10;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const stmtLines = doc.splitTextToSize(userData.statement, pageWidth - 40);
    doc.text(stmtLines, 20, y);
    y += (stmtLines.length * 5) + 10;
  }
  
  // Top Matches
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Top Company Matches", 20, y);
  y += 10;
  
  matches.forEach((match, i) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}. ${match.name} (${match.matchScore}%)`, 20, y);
    y += 6;
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    const reasonLines = doc.splitTextToSize(match.matchReason, pageWidth - 50);
    doc.text(reasonLines, 25, y);
    y += (reasonLines.length * 4) + 6;
  });
  
  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Basely.Connect on ${new Date().toLocaleDateString()}`, pageWidth / 2, 285, { align: "center" });
  }
  
  doc.save(`${userData.username}_portfolio.pdf`);
}
